xcodeproj 'TEMPLATE.xcodeproj'

platform :ios, '7.0'

target :"TEMPLATE-iOS-ARC" do
    platform :ios, '7.0'
end

target :"TEMPLATE-OSX-32-MRC" do
    platform :osx, '10.6'
end

target :"TEMPLATE-OSX-64-MRC" do
    platform :osx, '10.6'
end

target :"TEMPLATE-OSX-64-ARC" do
    platform :osx, '10.6'
end

target :"TEMPLATE-OSX-Universal-MRC" do
    platform :osx, '10.6'
end